"""
OneExtraction — Database Configuration
Auto-generated by setup_postgres.py
"""

POSTGRES_CONFIG = {
    "host":     "127.0.0.1",
    "port":     5432,
    "dbname":   "oneextraction",
    "user":     "postgres",
    "password": "7903",
}

DATABASE_URL = "postgresql://postgres:7903@127.0.0.1:5432/oneextraction"
SQLITE_URL   = "sqlite:///output/us/api/oneextraction.db"

# Set this to switch between databases
ACTIVE_DB = "postgresql"  # or "sqlite"
